apiVersion: v1
kind: Service
metadata:
  name: content-engine-service
spec:
    selector:
      app: content-engine
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080