#apiVersion: v1
#kind: Pod
#metadata:
#  name: content-engine-poda  # Name of your pod
#  labels:
#    app: content-engine     # Label for organization
#spec:
#  containers:
#    - name: content-engine    # Name of the container
#      image: srivardhanrr/content-engine:latest # Your image
#      env:
#        - name: PORT
#          value: "8080"
#        - name: WELCOME_MSG
#          value: "Hello, World!"
#      envFrom:
#        - secretRef:
#            name: content-engine-configmap
#      ports:
#        - containerPort: 8080